"""Generate the paper's per-corpus appendix table from data/merged_analysis.csv.
Lists every active corpus (role, source, domain, alpha, H_inf, BPC@32K, turns),
grouped by role and sorted by H_inf desc. Regenerate whenever the registry grows.
Writes paper/appendix_corpus_table.md."""
import csv
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent
rows = [r for r in csv.DictReader(open(ROOT / "data" / "merged_analysis.csv"))
        if r["role"] != "EXCLUDED"]
ROLE_ORDER = ["EVAL_TASK", "EVAL_TRAJ", "TRAIN"]
ROLE_NAME = {"EVAL_TASK": "Evaluation / benchmark task corpora",
             "EVAL_TRAJ": "Evaluation rollouts (agent runs on a benchmark)",
             "TRAIN": "Training trajectories"}
out = ["# Appendix A — Per-corpus table (auto-generated)\n",
       f"*All {len(rows)} active corpora (6 fit-artifact rows excluded). "
       "Reference-exact (α, H∞); BPC@32K directly measured; turns = mean per episode. "
       "Generated by `scripts/make_appendix_table.py` from `data/merged_analysis.csv`.*\n"]
for role in ROLE_ORDER:
    grp = sorted((r for r in rows if r["role"] == role),
                 key=lambda r: -float(r["h_inf"]))
    out.append(f"\n## {ROLE_NAME[role]}  (n={len(grp)})\n")
    out.append("| dataset (slug) | source | domain | α | H∞ | BPC@32K | turns |")
    out.append("| :-- | :-- | :-- | --: | --: | --: | --: |")
    for r in grp:
        out.append(f"| {r['slug']} | {r['source']} | {r['domain']} | "
                   f"{float(r['alpha']):.2f} | {float(r['h_inf']):.2f} | "
                   f"{float(r['bpc_32768']):.2f} | {r['mean_turns']} |")
(ROOT / "paper" / "appendix_corpus_table.md").write_text("\n".join(out) + "\n")
print(f"wrote paper/appendix_corpus_table.md ({len(rows)} corpora)")
